insert into items (name) values ('Red Violin, The (Violon rouge, Le)');
insert into items (name) values ('Training Day');
insert into items (name) values ('Daughter of Dr. Jeckyll');
insert into items (name) values ('Loser Takes All, The (O hamenos ta pairnei ola)');
insert into items (name) values ('Devil''s Doorway');
insert into items (name) values ('Change of Plans (Le code a changé)');
insert into items (name) values ('Documentarian');
insert into items (name) values ('Nothing Sacred');
insert into items (name) values ('Lake House, The');
insert into items (name) values ('Attila');
insert into items (name) values ('I Like It Like That');
insert into items (name) values ('Breaking News (Daai si gin)');
insert into items (name) values ('Lady in White (a.k.a. The Mystery of the Lady in White)');
insert into items (name) values ('Iron Eagle IV');
insert into items (name) values ('House Party 2');
insert into items (name) values ('Eight Below');
insert into items (name) values ('Cold Comfort Farm');
insert into items (name) values ('Ninja Cheerleaders');
insert into items (name) values ('Prime of Miss Jean Brodie, The');
insert into items (name) values ('Blood on the Moon');